### ISSUE TITLE
Why is both --server and --hostname required when using your own bind server?

### ISSUE THREAD

**Issue by josenk** [thekuwayama/nslookupot#6]
Why is both '--server' and '--hostname' required when using your own bind server?  Is there a way to do your query by simply providing the IP address?  (just like the regular nslookup command)

If you specify only one of the above parameters, you get a 'does not match the server certificate' error.

**Comment by thekuwayama** [comment]
`nslookupot` does not provide the feature that does not check the hostname.

It communicates with the DNS server via TLS and checks hostname.
So, it raises the error when not matched the hostname.

You could check the SANs of the certificate installed by the DNS server, specify '--hostname'. Thank you!

**Comment by thekuwayama** [comment]
You could get SANs with:

```
$ echo | openssl s_client -connect $YOUR_SERVER:$YOUR_PORT 2>/dev/null | openssl x509 -noout -ext subjectAltName
```

**Comment by thekuwayama** [comment]
@josenk 
[nslookupot-0.0.5](https://rubygems.org/gems/nslookupot/versions/0.0.5) has supported the feature that does not check the hostname(SNI).
You could run it with `--no-check-sni` option. 👍 

```
$ nslookupot --no-check-sni --server $YOUR_SERVER example.com
```
